backend:
  name: git-gateway
  branch: master
media_folder: '/public/uploads'
public_folder: '/uploads'
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "_content/home.yml"
        fields:
          - label: "Sections"
            name: "sections"
            widget: "list"
            required: false
            fields:
              - label: "Section Title"
                name: "section-title"
                required: false
                widget: text
              - label: "Section Color"
                name: "section-color"
                required: false
                widget: text
              - label: "Section Content"
                name: "section-content"
                widget: "list"
                required: false
                types:
                  - label: "Text with Image"
                    name: "text-with-image"
                    widget: object
                    required: false
                    fields:
                      - {label: Text, name: text, widget: markdown, required: false}
                      - {label: Image, name: image, widget: image, required: false}
                  - label: "Accordions"
                    name: "accordions"
                    widget: list
                    required: false
                    fields:
                      - {label: Title, name: title, widget: text, required: false}
                      - {label: Content, name: content, widget: markdown, required: false}