backend:
  name: git-gateway
  branch: master
media_folder: '/public/uploads'
public_folder: '/uploads'
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "_content/home.yml"
        create: true
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Photo, name: photo, widget: image}
  # - name: "home" # Used in routes, e.g., /admin/collections/blog
  #   label: "Home" # Used in the UI
  #   file: "_content/home.yml" # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   slug: "home" # Filename template, e.g., YYYY-MM-DD-title.md
  #   fields: # The fields for each document, usually in front matter
  #     - label: "Sections"
  #       name: "sections"
  #       widget: "list"
  #       fields:
  #         - label: "Section Title"
  #           name: "section-title"
  #           widget: text
  #         - label: "Section Color"
  #           name: "section-color"
  #           widget: text
  #         - label: "Section Content"
  #           name: "section-content"
  #           widget: "list"
  #           types:
  #             - label: "Text with Image"
  #               name: "text-with-image"
  #               widget: object
  #               fields:
  #                 - {label: Text, name: text, widget: markdown}
  #                 - {label: Image, name: image, widget: image}
  #             - label: "Accordions"
  #               name: "accordions"
  #               widget: list
  #               fields:
  #                 - {label: Title, name: title, widget: text}
  #                 - {label: Content, name: content, widget: markdown}